= Licences

Il existe deux licences régisseant ce projet.

A l'exclusion des images générées par IA (voir + bas), l'ensemble de la production sur ce repository  est gérée sous la licence link:https://creativecommons.org/licenses/by-nc-sa/4.0/[by-nc-sa V4.0] ce qui signifie que 

 * Vous êtes autorisé à : **Partager** — copier, distribuer et communiquer le matériel par tous moyens et sous tous formats
 * Vous êtes autorisé à : **Adapter** — remixer, transformer et créer à partir du matériel

Selon les conditions suivantes :

 * **Attribution** — Vous devez créditer l'Œuvre, intégrer un lien vers la licence et indiquer si des modifications ont été effectuées à l'Oeuvre. Vous devez indiquer ces informations par tous les moyens raisonnables, sans toutefois suggérer que l'Offrant vous soutient ou soutient la façon dont vous avez utilisé son Oeuvre.
 * **Pas d’Utilisation Commerciale** — Vous n'êtes pas autorisé à faire un usage commercial de cette Oeuvre, tout ou partie du matériel la composant.
 * **Partage dans les Mêmes Conditions** — Dans le cas où vous effectuez un remix, que vous transformez, ou créez à partir du matériel composant l'Oeuvre originale, vous devez diffuser l'Oeuvre modifiée dans les même conditions, c'est à dire avec la même licence avec laquelle l'Oeuvre originale a été diffusée.

(source de la description : link:https://creativecommons.org/licenses/by-nc-sa/4.0/[by-nc-sa V4.0])

== Code source de génération des images

 * Python (link:https://fr.wikipedia.org/wiki/Python_Software_Foundation_License[Python Software Foundation License compatible GPL])
 * OpenCV (link:https://opencv.org/license/[Apache2 Licence])
 * Code source de l'auteur : (link:https://creativecommons.org/licenses/by-nc-sa/4.0/[by-nc-sa V4.0] et version link:https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr[FR])

== Sources d'images

Les images utilisées pour illustrer l'ensemble du jeu ont été généré via différentes solutions dont voici la liste

 * Géneration des items de l'inventaire (link:https://huggingface.co/proximasanfinetuning/fantassified_icons_v2[lien])
 * Génération des biomes, des points d'intérêt, des particularite et des enjeux (link:https://beta.dreamstudio.ai/generate[lien])

L'ensemble des images générées sont libres de droit (copyleft) (link:https://www.alenknight.com/?p=2276[en savoir plus])